insert into accidens (contract_id, date_dtp, result) values (1, '19/7/2021', 'sed ante vivamus tortor duis mattis');
insert into accidens (contract_id, date_dtp, result) values (2, '24/10/2021', 'sed augue aliquam erat volutpat in');
insert into accidens (contract_id, date_dtp, result) values (3, '13/12/2021', 'erat nulla tempus vivamus in felis eu');
insert into accidens (contract_id, date_dtp, result) values (4, '5/1/2022', 'sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into accidens (contract_id, date_dtp, result) values (5, '29/11/2021', 'duis bibendum morbi non quam nec dui');
insert into accidens (contract_id, date_dtp, result) values (6, '10/12/2021', 'nulla neque libero convallis eget eleifend luctus');
insert into accidens (contract_id, date_dtp, result) values (7, '29/1/2022', 'blandit non interdum in ante vestibulum ante ipsum');
insert into accidens (contract_id, date_dtp, result) values (8, '27/4/2021', 'vestibulum sagittis sapien cum sociis natoque');
insert into accidens (contract_id, date_dtp, result) values (9, '6/2/2022', 'eros suspendisse accumsan tortor quis turpis');
insert into accidens (contract_id, date_dtp, result) values (10, '17/1/2022', 'nec dui luctus rutrum nulla tellus in sagittis');
insert into accidens (contract_id, date_dtp, result) values (11, '12/10/2021', 'eget tempus vel pede morbi');
insert into accidens (contract_id, date_dtp, result) values (12, '9/5/2021', 'curabitur gravida nisi at nibh in');
insert into accidens (contract_id, date_dtp, result) values (13, '19/7/2021', 'viverra eget congue eget semper');
insert into accidens (contract_id, date_dtp, result) values (14, '25/4/2021', 'luctus et ultrices posuere cubilia curae mauris viverra');
insert into accidens (contract_id, date_dtp, result) values (15, '21/12/2021', 'tortor quis turpis sed ante');
insert into accidens (contract_id, date_dtp, result) values (16, '16/7/2021', 'morbi vestibulum velit id pretium iaculis diam');
insert into accidens (contract_id, date_dtp, result) values (17, '19/2/2021', 'ut odio cras mi pede malesuada');
insert into accidens (contract_id, date_dtp, result) values (18, '22/1/2022', 'risus praesent lectus vestibulum quam sapien');
insert into accidens (contract_id, date_dtp, result) values (19, '13/8/2021', 'aliquam erat volutpat in congue etiam justo etiam');
insert into accidens (contract_id, date_dtp, result) values (20, '16/2/2021', 'aliquet pulvinar sed nisl nunc rhoncus');
insert into accidens (contract_id, date_dtp, result) values (21, '11/5/2021', 'et ultrices posuere cubilia curae');
insert into accidens (contract_id, date_dtp, result) values (22, '20/4/2021', 'interdum mauris ullamcorper purus sit');
insert into accidens (contract_id, date_dtp, result) values (23, '19/7/2021', 'ac consequat metus sapien ut nunc');
insert into accidens (contract_id, date_dtp, result) values (24, '9/2/2022', 'cubilia curae mauris viverra diam vitae');
insert into accidens (contract_id, date_dtp, result) values (25, '21/12/2021', 'in tempor turpis nec euismod scelerisque quam');
insert into accidens (contract_id, date_dtp, result) values (26, '23/6/2021', 'ac diam cras pellentesque volutpat dui');
insert into accidens (contract_id, date_dtp, result) values (27, '21/10/2021', 'odio elementum eu interdum eu tincidunt');
insert into accidens (contract_id, date_dtp, result) values (28, '13/9/2021', 'faucibus orci luctus et ultrices posuere cubilia');
insert into accidens (contract_id, date_dtp, result) values (29, '12/4/2021', 'in tempus sit amet sem');
insert into accidens (contract_id, date_dtp, result) values (30, '8/9/2021', 'ipsum ac tellus semper interdum mauris');
insert into accidens (contract_id, date_dtp, result) values (31, '23/7/2021', 'viverra pede ac diam cras pellentesque');
insert into accidens (contract_id, date_dtp, result) values (32, '4/3/2021', 'nec sem duis aliquam convallis nunc proin at');
insert into accidens (contract_id, date_dtp, result) values (33, '13/3/2021', 'nulla ac enim in tempor turpis nec euismod');
insert into accidens (contract_id, date_dtp, result) values (34, '15/11/2021', 'augue quam sollicitudin vitae consectetuer');
insert into accidens (contract_id, date_dtp, result) values (35, '16/2/2021', 'mauris enim leo rhoncus sed');
insert into accidens (contract_id, date_dtp, result) values (36, '10/7/2021', 'elit sodales scelerisque mauris sit amet eros suspendisse');
insert into accidens (contract_id, date_dtp, result) values (37, '15/9/2021', 'at dolor quis odio consequat');
insert into accidens (contract_id, date_dtp, result) values (38, '3/9/2021', 'nascetur ridiculus mus vivamus vestibulum sagittis');
insert into accidens (contract_id, date_dtp, result) values (39, '1/5/2021', 'eleifend luctus ultricies eu nibh');
insert into accidens (contract_id, date_dtp, result) values (40, '26/5/2021', 'quam fringilla rhoncus mauris enim');
insert into accidens (contract_id, date_dtp, result) values (41, '13/9/2021', 'nullam varius nulla facilisi cras non');
insert into accidens (contract_id, date_dtp, result) values (42, '22/2/2021', 'lacus morbi sem mauris laoreet');
insert into accidens (contract_id, date_dtp, result) values (43, '19/8/2021', 'sit amet turpis elementum ligula vehicula');
insert into accidens (contract_id, date_dtp, result) values (44, '27/4/2021', 'ultrices erat tortor sollicitudin mi sit amet lobortis');
insert into accidens (contract_id, date_dtp, result) values (45, '11/4/2021', 'vestibulum ante ipsum primis in faucibus orci luctus');
insert into accidens (contract_id, date_dtp, result) values (46, '25/9/2021', 'amet nunc viverra dapibus nulla');
insert into accidens (contract_id, date_dtp, result) values (47, '3/11/2021', 'at feugiat non pretium quis lectus suspendisse potenti');
insert into accidens (contract_id, date_dtp, result) values (48, '19/1/2022', 'posuere cubilia curae duis faucibus');
insert into accidens (contract_id, date_dtp, result) values (49, '23/4/2021', 'nibh in hac habitasse platea dictumst');
insert into accidens (contract_id, date_dtp, result) values (50, '28/10/2021', 'aliquam convallis nunc proin at turpis a');
insert into accidens (contract_id, date_dtp, result) values (51, '13/6/2021', 'pulvinar sed nisl nunc rhoncus dui vel sem');
insert into accidens (contract_id, date_dtp, result) values (52, '12/11/2021', 'massa quis augue luctus tincidunt');
insert into accidens (contract_id, date_dtp, result) values (53, '21/9/2021', 'vel enim sit amet nunc');
insert into accidens (contract_id, date_dtp, result) values (54, '30/10/2021', 'sem fusce consequat nulla nisl nunc');
insert into accidens (contract_id, date_dtp, result) values (55, '10/9/2021', 'dui luctus rutrum nulla tellus in');
insert into accidens (contract_id, date_dtp, result) values (56, '10/6/2021', 'a odio in hac habitasse');
insert into accidens (contract_id, date_dtp, result) values (57, '30/5/2021', 'molestie nibh in lectus pellentesque at nulla');
insert into accidens (contract_id, date_dtp, result) values (58, '20/6/2021', 'augue a suscipit nulla elit ac');
insert into accidens (contract_id, date_dtp, result) values (59, '27/6/2021', 'lorem quisque ut erat curabitur');
insert into accidens (contract_id, date_dtp, result) values (60, '7/5/2021', 'morbi sem mauris laoreet ut rhoncus');
insert into accidens (contract_id, date_dtp, result) values (61, '3/7/2021', 'sit amet justo morbi ut');
insert into accidens (contract_id, date_dtp, result) values (62, '28/8/2021', 'parturient montes nascetur ridiculus mus');
insert into accidens (contract_id, date_dtp, result) values (63, '31/10/2021', 'magna bibendum imperdiet nullam orci pede venenatis non');
insert into accidens (contract_id, date_dtp, result) values (64, '12/2/2021', 'nullam varius nulla facilisi cras');
insert into accidens (contract_id, date_dtp, result) values (65, '3/4/2021', 'quisque erat eros viverra eget congue eget');
insert into accidens (contract_id, date_dtp, result) values (66, '10/11/2021', 'arcu sed augue aliquam erat');
insert into accidens (contract_id, date_dtp, result) values (67, '16/5/2021', 'in faucibus orci luctus et');
insert into accidens (contract_id, date_dtp, result) values (68, '11/7/2021', 'semper est quam pharetra magna');
insert into accidens (contract_id, date_dtp, result) values (69, '24/8/2021', 'maecenas tristique est et tempus semper est');
insert into accidens (contract_id, date_dtp, result) values (70, '6/3/2021', 'viverra eget congue eget semper rutrum nulla nunc');
insert into accidens (contract_id, date_dtp, result) values (71, '8/5/2021', 'ultrices posuere cubilia curae donec');
insert into accidens (contract_id, date_dtp, result) values (72, '23/5/2021', 'potenti nullam porttitor lacus at turpis donec posuere');
insert into accidens (contract_id, date_dtp, result) values (73, '29/4/2021', 'ac enim in tempor turpis nec euismod');
insert into accidens (contract_id, date_dtp, result) values (74, '11/7/2021', 'nunc purus phasellus in felis');
insert into accidens (contract_id, date_dtp, result) values (75, '30/1/2022', 'at ipsum ac tellus semper');
insert into accidens (contract_id, date_dtp, result) values (76, '20/12/2021', 'fringilla rhoncus mauris enim leo');
insert into accidens (contract_id, date_dtp, result) values (77, '2/2/2022', 'orci nullam molestie nibh in lectus pellentesque at');
insert into accidens (contract_id, date_dtp, result) values (78, '18/5/2021', 'amet erat nulla tempus vivamus in');
insert into accidens (contract_id, date_dtp, result) values (79, '10/12/2021', 'vitae quam suspendisse potenti nullam porttitor lacus at');
insert into accidens (contract_id, date_dtp, result) values (80, '13/3/2021', 'sed justo pellentesque viverra pede ac diam');
insert into accidens (contract_id, date_dtp, result) values (81, '27/6/2021', 'ligula pellentesque ultrices phasellus id sapien');
insert into accidens (contract_id, date_dtp, result) values (82, '6/2/2022', 'bibendum felis sed interdum venenatis turpis enim blandit');
insert into accidens (contract_id, date_dtp, result) values (83, '28/10/2021', 'ac est lacinia nisi venenatis tristique fusce congue');
insert into accidens (contract_id, date_dtp, result) values (84, '4/8/2021', 'cubilia curae donec pharetra magna');
insert into accidens (contract_id, date_dtp, result) values (85, '26/4/2021', 'in magna bibendum imperdiet nullam orci pede venenatis');
insert into accidens (contract_id, date_dtp, result) values (86, '24/3/2021', 'blandit ultrices enim lorem ipsum dolor sit');
insert into accidens (contract_id, date_dtp, result) values (87, '9/5/2021', 'nonummy integer non velit donec');
insert into accidens (contract_id, date_dtp, result) values (88, '24/1/2022', 'curabitur convallis duis consequat dui nec');
insert into accidens (contract_id, date_dtp, result) values (89, '20/7/2021', 'convallis tortor risus dapibus augue vel accumsan tellus');
insert into accidens (contract_id, date_dtp, result) values (90, '18/6/2021', 'nec nisi vulputate nonummy maecenas');
insert into accidens (contract_id, date_dtp, result) values (91, '11/1/2022', 'sit amet eros suspendisse accumsan tortor');
insert into accidens (contract_id, date_dtp, result) values (92, '15/7/2021', 'suscipit ligula in lacus curabitur at ipsum ac');
insert into accidens (contract_id, date_dtp, result) values (93, '30/8/2021', 'in ante vestibulum ante ipsum');
insert into accidens (contract_id, date_dtp, result) values (94, '22/6/2021', 'aliquam quis turpis eget elit sodales scelerisque mauris');
insert into accidens (contract_id, date_dtp, result) values (95, '4/11/2021', 'elementum in hac habitasse platea dictumst morbi');
insert into accidens (contract_id, date_dtp, result) values (96, '7/4/2021', 'cum sociis natoque penatibus et');
insert into accidens (contract_id, date_dtp, result) values (97, '3/4/2021', 'lectus pellentesque at nulla suspendisse');
insert into accidens (contract_id, date_dtp, result) values (98, '15/11/2021', 'suspendisse accumsan tortor quis turpis sed ante');
insert into accidens (contract_id, date_dtp, result) values (99, '16/6/2021', 'pellentesque viverra pede ac diam cras pellentesque');
insert into accidens (contract_id, date_dtp, result) values (100, '18/12/2021', 'placerat praesent blandit nam nulla integer');
insert into accidens (contract_id, date_dtp, result) values (101, '6/6/2021', 'ipsum integer a nibh in');
insert into accidens (contract_id, date_dtp, result) values (102, '1/5/2021', 'in tempus sit amet sem fusce consequat');
insert into accidens (contract_id, date_dtp, result) values (103, '25/11/2021', 'amet diam in magna bibendum imperdiet nullam orci');
insert into accidens (contract_id, date_dtp, result) values (104, '19/7/2021', 'ipsum primis in faucibus orci');
insert into accidens (contract_id, date_dtp, result) values (105, '5/6/2021', 'felis fusce posuere felis sed');
insert into accidens (contract_id, date_dtp, result) values (106, '3/4/2021', 'suspendisse ornare consequat lectus in est');
insert into accidens (contract_id, date_dtp, result) values (107, '16/8/2021', 'ut dolor morbi vel lectus');
insert into accidens (contract_id, date_dtp, result) values (108, '1/1/2022', 'ante ipsum primis in faucibus orci luctus et');
insert into accidens (contract_id, date_dtp, result) values (109, '26/5/2021', 'phasellus sit amet erat nulla tempus vivamus in');
insert into accidens (contract_id, date_dtp, result) values (110, '20/11/2021', 'pellentesque ultrices mattis odio donec vitae nisi');
insert into accidens (contract_id, date_dtp, result) values (111, '18/3/2021', 'lobortis ligula sit amet eleifend pede libero');
insert into accidens (contract_id, date_dtp, result) values (112, '29/5/2021', 'suspendisse ornare consequat lectus in est risus auctor');
insert into accidens (contract_id, date_dtp, result) values (113, '30/7/2021', 'a nibh in quis justo maecenas rhoncus');
insert into accidens (contract_id, date_dtp, result) values (114, '22/4/2021', 'odio condimentum id luctus nec molestie sed justo');
insert into accidens (contract_id, date_dtp, result) values (115, '12/8/2021', 'blandit ultrices enim lorem ipsum');
insert into accidens (contract_id, date_dtp, result) values (116, '24/11/2021', 'cursus urna ut tellus nulla ut erat id');
insert into accidens (contract_id, date_dtp, result) values (117, '20/11/2021', 'urna ut tellus nulla ut');
insert into accidens (contract_id, date_dtp, result) values (118, '1/3/2021', 'nulla facilisi cras non velit');
insert into accidens (contract_id, date_dtp, result) values (119, '10/2/2021', 'sem praesent id massa id nisl venenatis lacinia');
insert into accidens (contract_id, date_dtp, result) values (120, '8/11/2021', 'eu massa donec dapibus duis at');
insert into accidens (contract_id, date_dtp, result) values (121, '14/10/2021', 'lacus purus aliquet at feugiat non');
insert into accidens (contract_id, date_dtp, result) values (122, '4/1/2022', 'vel nisl duis ac nibh fusce');
insert into accidens (contract_id, date_dtp, result) values (123, '14/5/2021', 'imperdiet et commodo vulputate justo in');
insert into accidens (contract_id, date_dtp, result) values (124, '19/2/2021', 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien');
insert into accidens (contract_id, date_dtp, result) values (125, '23/2/2021', 'nec molestie sed justo pellentesque viverra');
insert into accidens (contract_id, date_dtp, result) values (126, '7/11/2021', 'potenti in eleifend quam a odio in');
insert into accidens (contract_id, date_dtp, result) values (127, '13/8/2021', 'in tempus sit amet sem');
insert into accidens (contract_id, date_dtp, result) values (128, '14/6/2021', 'leo odio condimentum id luctus nec molestie sed');
insert into accidens (contract_id, date_dtp, result) values (129, '6/9/2021', 'nisl aenean lectus pellentesque eget nunc');
insert into accidens (contract_id, date_dtp, result) values (130, '6/1/2022', 'phasellus id sapien in sapien iaculis congue');
insert into accidens (contract_id, date_dtp, result) values (131, '8/9/2021', 'pharetra magna ac consequat metus');
insert into accidens (contract_id, date_dtp, result) values (132, '9/9/2021', 'convallis eget eleifend luctus ultricies eu nibh');
insert into accidens (contract_id, date_dtp, result) values (133, '10/6/2021', 'cras pellentesque volutpat dui maecenas tristique est');
insert into accidens (contract_id, date_dtp, result) values (134, '17/2/2021', 'luctus et ultrices posuere cubilia');
insert into accidens (contract_id, date_dtp, result) values (135, '23/10/2021', 'potenti in eleifend quam a odio in');
insert into accidens (contract_id, date_dtp, result) values (136, '9/4/2021', 'id ligula suspendisse ornare consequat lectus in est');
insert into accidens (contract_id, date_dtp, result) values (137, '9/12/2021', 'ac diam cras pellentesque volutpat dui maecenas');
insert into accidens (contract_id, date_dtp, result) values (138, '29/5/2021', 'natoque penatibus et magnis dis');
insert into accidens (contract_id, date_dtp, result) values (139, '24/11/2021', 'odio justo sollicitudin ut suscipit a');
insert into accidens (contract_id, date_dtp, result) values (140, '27/6/2021', 'posuere cubilia curae mauris viverra');
insert into accidens (contract_id, date_dtp, result) values (141, '27/10/2021', 'elit proin risus praesent lectus');
insert into accidens (contract_id, date_dtp, result) values (142, '30/7/2021', 'quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into accidens (contract_id, date_dtp, result) values (143, '17/9/2021', 'commodo vulputate justo in blandit ultrices enim lorem');
insert into accidens (contract_id, date_dtp, result) values (144, '20/1/2022', 'nunc donec quis orci eget');
insert into accidens (contract_id, date_dtp, result) values (145, '2/2/2022', 'cubilia curae nulla dapibus dolor vel est donec');
insert into accidens (contract_id, date_dtp, result) values (146, '28/2/2021', 'sit amet eros suspendisse accumsan');
insert into accidens (contract_id, date_dtp, result) values (147, '16/11/2021', 'tincidunt lacus at velit vivamus vel');
insert into accidens (contract_id, date_dtp, result) values (148, '20/11/2021', 'in lectus pellentesque at nulla suspendisse potenti cras');
insert into accidens (contract_id, date_dtp, result) values (149, '2/8/2021', 'rutrum neque aenean auctor gravida sem');
insert into accidens (contract_id, date_dtp, result) values (150, '24/12/2021', 'lacus at turpis donec posuere metus');
insert into accidens (contract_id, date_dtp, result) values (151, '17/7/2021', 'in lacus curabitur at ipsum ac tellus semper');
insert into accidens (contract_id, date_dtp, result) values (152, '22/7/2021', 'dictumst etiam faucibus cursus urna');
insert into accidens (contract_id, date_dtp, result) values (153, '3/8/2021', 'suspendisse potenti in eleifend quam');
insert into accidens (contract_id, date_dtp, result) values (154, '3/1/2022', 'pede justo eu massa donec dapibus duis');
insert into accidens (contract_id, date_dtp, result) values (155, '14/5/2021', 'enim leo rhoncus sed vestibulum sit');
insert into accidens (contract_id, date_dtp, result) values (156, '20/9/2021', 'montes nascetur ridiculus mus etiam vel');
insert into accidens (contract_id, date_dtp, result) values (157, '17/8/2021', 'ullamcorper augue a suscipit nulla elit ac nulla');
insert into accidens (contract_id, date_dtp, result) values (158, '24/10/2021', 'at lorem integer tincidunt ante vel ipsum praesent');
insert into accidens (contract_id, date_dtp, result) values (159, '10/3/2021', 'pellentesque eget nunc donec quis orci');
insert into accidens (contract_id, date_dtp, result) values (160, '30/7/2021', 'eget massa tempor convallis nulla neque libero convallis');
insert into accidens (contract_id, date_dtp, result) values (161, '13/3/2021', 'magna at nunc commodo placerat praesent');
insert into accidens (contract_id, date_dtp, result) values (162, '31/8/2021', 'justo eu massa donec dapibus');
insert into accidens (contract_id, date_dtp, result) values (163, '4/8/2021', 'nec sem duis aliquam convallis nunc proin');
insert into accidens (contract_id, date_dtp, result) values (164, '20/12/2021', 'cursus vestibulum proin eu mi nulla');
insert into accidens (contract_id, date_dtp, result) values (165, '16/2/2021', 'curabitur in libero ut massa volutpat convallis morbi');
insert into accidens (contract_id, date_dtp, result) values (166, '30/8/2021', 'ultrices aliquet maecenas leo odio condimentum');
insert into accidens (contract_id, date_dtp, result) values (167, '12/2/2021', 'maecenas leo odio condimentum id luctus');
insert into accidens (contract_id, date_dtp, result) values (168, '30/5/2021', 'viverra diam vitae quam suspendisse potenti nullam porttitor');
insert into accidens (contract_id, date_dtp, result) values (169, '15/11/2021', 'volutpat convallis morbi odio odio elementum eu interdum');
insert into accidens (contract_id, date_dtp, result) values (170, '19/7/2021', 'neque aenean auctor gravida sem');
insert into accidens (contract_id, date_dtp, result) values (171, '13/12/2021', 'auctor sed tristique in tempus');
insert into accidens (contract_id, date_dtp, result) values (172, '20/10/2021', 'libero rutrum ac lobortis vel dapibus');
insert into accidens (contract_id, date_dtp, result) values (173, '12/7/2021', 'justo maecenas rhoncus aliquam lacus morbi quis tortor');
insert into accidens (contract_id, date_dtp, result) values (174, '11/10/2021', 'magnis dis parturient montes nascetur');
insert into accidens (contract_id, date_dtp, result) values (175, '12/3/2021', 'eros vestibulum ac est lacinia nisi venenatis');
insert into accidens (contract_id, date_dtp, result) values (176, '17/3/2021', 'massa id nisl venenatis lacinia');
insert into accidens (contract_id, date_dtp, result) values (177, '3/7/2021', 'pellentesque ultrices phasellus id sapien');
insert into accidens (contract_id, date_dtp, result) values (178, '11/8/2021', 'morbi ut odio cras mi pede malesuada');
insert into accidens (contract_id, date_dtp, result) values (179, '15/7/2021', 'donec pharetra magna vestibulum aliquet ultrices');
insert into accidens (contract_id, date_dtp, result) values (180, '20/5/2021', 'sapien urna pretium nisl ut');
insert into accidens (contract_id, date_dtp, result) values (181, '26/4/2021', 'sagittis nam congue risus semper porta volutpat');
insert into accidens (contract_id, date_dtp, result) values (182, '18/11/2021', 'suspendisse potenti in eleifend quam a');
insert into accidens (contract_id, date_dtp, result) values (183, '4/4/2021', 'pretium quis lectus suspendisse potenti in eleifend quam');
insert into accidens (contract_id, date_dtp, result) values (184, '14/7/2021', 'proin interdum mauris non ligula pellentesque ultrices phasellus');
insert into accidens (contract_id, date_dtp, result) values (185, '10/3/2021', 'nibh ligula nec sem duis aliquam convallis');
insert into accidens (contract_id, date_dtp, result) values (186, '10/9/2021', 'ac leo pellentesque ultrices mattis odio donec');
insert into accidens (contract_id, date_dtp, result) values (187, '2/1/2022', 'sed augue aliquam erat volutpat in congue etiam');
insert into accidens (contract_id, date_dtp, result) values (188, '15/10/2021', 'vel lectus in quam fringilla rhoncus mauris');
insert into accidens (contract_id, date_dtp, result) values (189, '27/4/2021', 'sapien in sapien iaculis congue vivamus metus');
insert into accidens (contract_id, date_dtp, result) values (190, '7/6/2021', 'donec vitae nisi nam ultrices');
insert into accidens (contract_id, date_dtp, result) values (191, '20/12/2021', 'velit eu est congue elementum in hac habitasse');
insert into accidens (contract_id, date_dtp, result) values (192, '4/2/2022', 'dui maecenas tristique est et tempus semper est');
insert into accidens (contract_id, date_dtp, result) values (193, '22/11/2021', 'orci luctus et ultrices posuere cubilia');
insert into accidens (contract_id, date_dtp, result) values (194, '20/11/2021', 'lobortis sapien sapien non mi integer ac');
insert into accidens (contract_id, date_dtp, result) values (195, '16/5/2021', 'potenti nullam porttitor lacus at turpis');
insert into accidens (contract_id, date_dtp, result) values (196, '22/2/2021', 'sem mauris laoreet ut rhoncus');
insert into accidens (contract_id, date_dtp, result) values (197, '6/4/2021', 'sit amet consectetuer adipiscing elit');
insert into accidens (contract_id, date_dtp, result) values (198, '28/11/2021', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus');
insert into accidens (contract_id, date_dtp, result) values (199, '22/8/2021', 'cursus urna ut tellus nulla ut');
insert into accidens (contract_id, date_dtp, result) values (200, '30/11/2021', 'in hac habitasse platea dictumst etiam');
insert into accidens (contract_id, date_dtp, result) values (201, '26/4/2021', 'convallis eget eleifend luctus ultricies');
insert into accidens (contract_id, date_dtp, result) values (202, '20/10/2021', 'justo in hac habitasse platea dictumst etiam');
insert into accidens (contract_id, date_dtp, result) values (203, '6/11/2021', 'id luctus nec molestie sed justo pellentesque viverra');
insert into accidens (contract_id, date_dtp, result) values (204, '12/11/2021', 'sagittis nam congue risus semper porta volutpat');
insert into accidens (contract_id, date_dtp, result) values (205, '19/6/2021', 'venenatis turpis enim blandit mi in porttitor');
insert into accidens (contract_id, date_dtp, result) values (206, '23/1/2022', 'ut dolor morbi vel lectus');
insert into accidens (contract_id, date_dtp, result) values (207, '1/10/2021', 'lorem vitae mattis nibh ligula nec sem');
insert into accidens (contract_id, date_dtp, result) values (208, '1/4/2021', 'nisl aenean lectus pellentesque eget');
insert into accidens (contract_id, date_dtp, result) values (209, '17/8/2021', 'suspendisse accumsan tortor quis turpis sed ante');
insert into accidens (contract_id, date_dtp, result) values (210, '9/8/2021', 'ante ipsum primis in faucibus orci luctus');
insert into accidens (contract_id, date_dtp, result) values (211, '18/12/2021', 'et magnis dis parturient montes nascetur ridiculus mus');
insert into accidens (contract_id, date_dtp, result) values (212, '13/2/2021', 'phasellus in felis donec semper');
insert into accidens (contract_id, date_dtp, result) values (213, '8/8/2021', 'suscipit nulla elit ac nulla sed vel enim');
insert into accidens (contract_id, date_dtp, result) values (214, '18/8/2021', 'mattis nibh ligula nec sem');
insert into accidens (contract_id, date_dtp, result) values (215, '18/8/2021', 'mi in porttitor pede justo eu massa');
insert into accidens (contract_id, date_dtp, result) values (216, '6/6/2021', 'sapien iaculis congue vivamus metus arcu');
insert into accidens (contract_id, date_dtp, result) values (217, '5/6/2021', 'velit donec diam neque vestibulum eget vulputate');
insert into accidens (contract_id, date_dtp, result) values (218, '13/7/2021', 'eget semper rutrum nulla nunc purus phasellus');
insert into accidens (contract_id, date_dtp, result) values (219, '29/1/2022', 'penatibus et magnis dis parturient montes nascetur');
insert into accidens (contract_id, date_dtp, result) values (220, '15/6/2021', 'blandit ultrices enim lorem ipsum dolor sit');
insert into accidens (contract_id, date_dtp, result) values (221, '5/12/2021', 'justo sit amet sapien dignissim vestibulum');
insert into accidens (contract_id, date_dtp, result) values (222, '26/11/2021', 'vivamus tortor duis mattis egestas metus aenean');
insert into accidens (contract_id, date_dtp, result) values (223, '5/10/2021', 'turpis enim blandit mi in');
insert into accidens (contract_id, date_dtp, result) values (224, '6/6/2021', 'sed magna at nunc commodo placerat');
insert into accidens (contract_id, date_dtp, result) values (225, '14/6/2021', 'sit amet consectetuer adipiscing elit proin risus');
insert into accidens (contract_id, date_dtp, result) values (226, '8/4/2021', 'elit proin risus praesent lectus vestibulum quam');
insert into accidens (contract_id, date_dtp, result) values (227, '2/5/2021', 'quis tortor id nulla ultrices aliquet maecenas leo');
insert into accidens (contract_id, date_dtp, result) values (228, '26/7/2021', 'nam dui proin leo odio porttitor');
insert into accidens (contract_id, date_dtp, result) values (229, '24/4/2021', 'consectetuer adipiscing elit proin risus');
insert into accidens (contract_id, date_dtp, result) values (230, '13/11/2021', 'semper rutrum nulla nunc purus phasellus in felis');
insert into accidens (contract_id, date_dtp, result) values (231, '24/2/2021', 'dolor vel est donec odio justo sollicitudin');
insert into accidens (contract_id, date_dtp, result) values (232, '15/10/2021', 'diam in magna bibendum imperdiet nullam orci pede');
insert into accidens (contract_id, date_dtp, result) values (233, '11/1/2022', 'etiam faucibus cursus urna ut tellus nulla ut');
insert into accidens (contract_id, date_dtp, result) values (234, '6/5/2021', 'tortor risus dapibus augue vel');
insert into accidens (contract_id, date_dtp, result) values (235, '10/4/2021', 'sollicitudin mi sit amet lobortis sapien');
insert into accidens (contract_id, date_dtp, result) values (236, '19/9/2021', 'posuere felis sed lacus morbi');
insert into accidens (contract_id, date_dtp, result) values (237, '5/12/2021', 'potenti cras in purus eu');
insert into accidens (contract_id, date_dtp, result) values (238, '26/3/2021', 'aliquam convallis nunc proin at');
insert into accidens (contract_id, date_dtp, result) values (239, '19/3/2021', 'erat vestibulum sed magna at nunc commodo');
insert into accidens (contract_id, date_dtp, result) values (240, '24/2/2021', 'magnis dis parturient montes nascetur');
insert into accidens (contract_id, date_dtp, result) values (241, '25/2/2021', 'mauris ullamcorper purus sit amet');
insert into accidens (contract_id, date_dtp, result) values (242, '13/9/2021', 'lacus at velit vivamus vel nulla');
insert into accidens (contract_id, date_dtp, result) values (243, '21/6/2021', 'a ipsum integer a nibh in quis justo');
insert into accidens (contract_id, date_dtp, result) values (244, '1/10/2021', 'tempus vel pede morbi porttitor lorem');
insert into accidens (contract_id, date_dtp, result) values (245, '18/5/2021', 'fusce posuere felis sed lacus morbi sem mauris');
insert into accidens (contract_id, date_dtp, result) values (246, '2/9/2021', 'tristique fusce congue diam id ornare imperdiet');
insert into accidens (contract_id, date_dtp, result) values (247, '8/12/2021', 'platea dictumst maecenas ut massa quis augue');
insert into accidens (contract_id, date_dtp, result) values (248, '13/7/2021', 'justo morbi ut odio cras mi pede malesuada');
insert into accidens (contract_id, date_dtp, result) values (249, '24/10/2021', 'ultrices posuere cubilia curae donec pharetra');
insert into accidens (contract_id, date_dtp, result) values (250, '3/6/2021', 'cras in purus eu magna vulputate luctus');
insert into accidens (contract_id, date_dtp, result) values (251, '26/6/2021', 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into accidens (contract_id, date_dtp, result) values (252, '9/11/2021', 'duis faucibus accumsan odio curabitur');
insert into accidens (contract_id, date_dtp, result) values (253, '22/2/2021', 'volutpat sapien arcu sed augue');
insert into accidens (contract_id, date_dtp, result) values (254, '29/4/2021', 'fusce posuere felis sed lacus morbi sem');
insert into accidens (contract_id, date_dtp, result) values (255, '18/12/2021', 'ante ipsum primis in faucibus orci');
insert into accidens (contract_id, date_dtp, result) values (256, '11/10/2021', 'sapien non mi integer ac neque duis bibendum');
insert into accidens (contract_id, date_dtp, result) values (257, '30/8/2021', 'integer ac neque duis bibendum morbi non');
insert into accidens (contract_id, date_dtp, result) values (258, '1/5/2021', 'ac est lacinia nisi venenatis');
insert into accidens (contract_id, date_dtp, result) values (259, '23/6/2021', 'ligula in lacus curabitur at ipsum ac');
insert into accidens (contract_id, date_dtp, result) values (260, '24/7/2021', 'integer ac neque duis bibendum morbi non quam');
insert into accidens (contract_id, date_dtp, result) values (261, '18/5/2021', 'ornare imperdiet sapien urna pretium');
insert into accidens (contract_id, date_dtp, result) values (262, '5/2/2022', 'mi pede malesuada in imperdiet et');
insert into accidens (contract_id, date_dtp, result) values (263, '8/11/2021', 'integer aliquet massa id lobortis convallis tortor');
insert into accidens (contract_id, date_dtp, result) values (264, '25/11/2021', 'augue aliquam erat volutpat in');
insert into accidens (contract_id, date_dtp, result) values (265, '17/7/2021', 'mattis odio donec vitae nisi');
insert into accidens (contract_id, date_dtp, result) values (266, '27/8/2021', 'at feugiat non pretium quis lectus suspendisse potenti');
insert into accidens (contract_id, date_dtp, result) values (267, '19/10/2021', 'in faucibus orci luctus et ultrices');
insert into accidens (contract_id, date_dtp, result) values (268, '14/8/2021', 'lectus in est risus auctor sed tristique in');
insert into accidens (contract_id, date_dtp, result) values (269, '6/7/2021', 'vestibulum vestibulum ante ipsum primis in');
insert into accidens (contract_id, date_dtp, result) values (270, '19/5/2021', 'nisl venenatis lacinia aenean sit');
insert into accidens (contract_id, date_dtp, result) values (271, '5/8/2021', 'blandit mi in porttitor pede justo eu massa');
insert into accidens (contract_id, date_dtp, result) values (272, '8/3/2021', 'pede justo eu massa donec dapibus duis at');
insert into accidens (contract_id, date_dtp, result) values (273, '14/11/2021', 'in hac habitasse platea dictumst morbi vestibulum velit');
insert into accidens (contract_id, date_dtp, result) values (274, '23/5/2021', 'vestibulum velit id pretium iaculis diam erat fermentum');
insert into accidens (contract_id, date_dtp, result) values (275, '24/9/2021', 'vestibulum sit amet cursus id turpis integer');
insert into accidens (contract_id, date_dtp, result) values (276, '11/12/2021', 'etiam pretium iaculis justo in hac habitasse platea');
insert into accidens (contract_id, date_dtp, result) values (277, '27/12/2021', 'ut nulla sed accumsan felis ut at dolor');
insert into accidens (contract_id, date_dtp, result) values (278, '30/9/2021', 'tempus vivamus in felis eu sapien cursus vestibulum');
insert into accidens (contract_id, date_dtp, result) values (279, '21/3/2021', 'et ultrices posuere cubilia curae mauris');
insert into accidens (contract_id, date_dtp, result) values (280, '26/1/2022', 'leo odio porttitor id consequat in consequat ut');
insert into accidens (contract_id, date_dtp, result) values (281, '19/9/2021', 'mauris ullamcorper purus sit amet nulla quisque');
insert into accidens (contract_id, date_dtp, result) values (282, '17/11/2021', 'leo maecenas pulvinar lobortis est phasellus sit');
insert into accidens (contract_id, date_dtp, result) values (283, '16/8/2021', 'tellus nisi eu orci mauris');
insert into accidens (contract_id, date_dtp, result) values (284, '20/6/2021', 'maecenas rhoncus aliquam lacus morbi quis tortor id');
insert into accidens (contract_id, date_dtp, result) values (285, '15/6/2021', 'turpis enim blandit mi in porttitor pede');
insert into accidens (contract_id, date_dtp, result) values (286, '28/12/2021', 'ut mauris eget massa tempor convallis');
insert into accidens (contract_id, date_dtp, result) values (287, '19/12/2021', 'posuere cubilia curae nulla dapibus dolor');
insert into accidens (contract_id, date_dtp, result) values (288, '5/1/2022', 'elit ac nulla sed vel enim sit amet');
insert into accidens (contract_id, date_dtp, result) values (289, '16/6/2021', 'leo pellentesque ultrices mattis odio donec vitae');
insert into accidens (contract_id, date_dtp, result) values (290, '24/2/2021', 'sapien arcu sed augue aliquam erat volutpat in');
insert into accidens (contract_id, date_dtp, result) values (291, '8/12/2021', 'convallis morbi odio odio elementum eu');
insert into accidens (contract_id, date_dtp, result) values (292, '29/12/2021', 'nisl duis bibendum felis sed');
insert into accidens (contract_id, date_dtp, result) values (293, '28/7/2021', 'proin leo odio porttitor id consequat in');
insert into accidens (contract_id, date_dtp, result) values (294, '21/10/2021', 'ligula vehicula consequat morbi a ipsum integer');
insert into accidens (contract_id, date_dtp, result) values (295, '31/8/2021', 'suspendisse potenti cras in purus');
insert into accidens (contract_id, date_dtp, result) values (296, '12/4/2021', 'nisl nunc nisl duis bibendum felis sed interdum');
insert into accidens (contract_id, date_dtp, result) values (297, '23/7/2021', 'eleifend donec ut dolor morbi vel lectus');
insert into accidens (contract_id, date_dtp, result) values (298, '27/3/2021', 'luctus et ultrices posuere cubilia curae nulla dapibus');
insert into accidens (contract_id, date_dtp, result) values (299, '4/9/2021', 'blandit mi in porttitor pede justo eu');
insert into accidens (contract_id, date_dtp, result) values (300, '30/3/2021', 'rutrum ac lobortis vel dapibus at diam nam');
