insert into model (id, model, brend, color) values (1, 'Tacoma Xtra', 'Toyota', 'Aquamarine');
insert into model (id, model, brend, color) values (2, 'Silverado 1500', 'Chevrolet', 'Violet');
insert into model (id, model, brend, color) values (3, 'Suburban 1500', 'GMC', 'Maroon');
insert into model (id, model, brend, color) values (4, 'RAV4', 'Toyota', 'Fuscia');
insert into model (id, model, brend, color) values (5, 'Sierra', 'GMC', 'Purple');
insert into model (id, model, brend, color) values (6, 'Park Avenue', 'Buick', 'Turquoise');
insert into model (id, model, brend, color) values (7, 'Savana 3500', 'GMC', 'Purple');
insert into model (id, model, brend, color) values (8, 'Canyon', 'GMC', 'Mauv');
insert into model (id, model, brend, color) values (9, 'Raider', 'Mitsubishi', 'Fuscia');
insert into model (id, model, brend, color) values (10, 'Continental GTC', 'Bentley', 'Aquamarine');
insert into model (id, model, brend, color) values (11, 'Sonata', 'Hyundai', 'Violet');
insert into model (id, model, brend, color) values (12, 'Veracruz', 'Hyundai', 'Violet');
insert into model (id, model, brend, color) values (13, 'V50', 'Volvo', 'Purple');
insert into model (id, model, brend, color) values (14, 'Grand Caravan', 'Dodge', 'Turquoise');
insert into model (id, model, brend, color) values (15, 'Park Avenue', 'Buick', 'Turquoise');
insert into model (id, model, brend, color) values (16, 'Mystique', 'Mercury', 'Mauv');
insert into model (id, model, brend, color) values (17, 'Grand Caravan', 'Dodge', 'Mauv');
insert into model (id, model, brend, color) values (18, 'DB9', 'Aston Martin', 'Orange');
insert into model (id, model, brend, color) values (19, '300ZX', 'Nissan', 'Goldenrod');
insert into model (id, model, brend, color) values (20, 'Focus', 'Ford', 'Yellow');
insert into model (id, model, brend, color) values (21, 'Passport', 'Honda', 'Purple');
insert into model (id, model, brend, color) values (22, 'LR2', 'Land Rover', 'Turquoise');
insert into model (id, model, brend, color) values (23, 'Dakota', 'Dodge', 'Purple');
insert into model (id, model, brend, color) values (24, 'Charger', 'Dodge', 'Blue');
insert into model (id, model, brend, color) values (25, 'SLR McLaren', 'Mercedes-Benz', 'Puce');
insert into model (id, model, brend, color) values (26, '911', 'Porsche', 'Blue');
insert into model (id, model, brend, color) values (27, 'Navigator', 'Lincoln', 'Indigo');
insert into model (id, model, brend, color) values (28, 'Thunderbird', 'Ford', 'Khaki');
insert into model (id, model, brend, color) values (29, 'GTI', 'Volkswagen', 'Purple');
insert into model (id, model, brend, color) values (30, 'Camaro', 'Chevrolet', 'Maroon');
insert into model (id, model, brend, color) values (31, 'LS', 'Lexus', 'Puce');
insert into model (id, model, brend, color) values (32, '9000', 'Saab', 'Teal');
insert into model (id, model, brend, color) values (33, 'Diablo', 'Lamborghini', 'Red');
insert into model (id, model, brend, color) values (34, '3 Series', 'BMW', 'Red');
insert into model (id, model, brend, color) values (35, 'XL-7', 'Suzuki', 'Mauv');
insert into model (id, model, brend, color) values (36, '1500 Club Coupe', 'GMC', 'Teal');
insert into model (id, model, brend, color) values (37, 'Sierra 1500', 'GMC', 'Green');
insert into model (id, model, brend, color) values (38, 'Marquis', 'Mercury', 'Fuscia');
insert into model (id, model, brend, color) values (39, 'S-Class', 'Mercedes-Benz', 'Violet');
insert into model (id, model, brend, color) values (40, 'Accent', 'Hyundai', 'Khaki');
insert into model (id, model, brend, color) values (41, '929', 'Mazda', 'Teal');
insert into model (id, model, brend, color) values (42, 'Fiesta', 'Ford', 'Blue');
insert into model (id, model, brend, color) values (43, 'S-Class', 'Mercedes-Benz', 'Green');
insert into model (id, model, brend, color) values (44, 'Arnage', 'Bentley', 'Violet');
insert into model (id, model, brend, color) values (45, 'Envoy', 'GMC', 'Red');
insert into model (id, model, brend, color) values (46, 'F350', 'Ford', 'Turquoise');
insert into model (id, model, brend, color) values (47, 'Ram 1500 Club', 'Dodge', 'Indigo');
insert into model (id, model, brend, color) values (48, 'Diablo', 'Lamborghini', 'Turquoise');
insert into model (id, model, brend, color) values (49, 'GLI', 'Volkswagen', 'Aquamarine');
insert into model (id, model, brend, color) values (50, '300CE', 'Mercedes-Benz', 'Fuscia');
insert into model (id, model, brend, color) values (51, 'Passat', 'Volkswagen', 'Fuscia');
insert into model (id, model, brend, color) values (52, 'Discovery', 'Land Rover', 'Khaki');
insert into model (id, model, brend, color) values (53, '600SEL', 'Mercedes-Benz', 'Blue');
insert into model (id, model, brend, color) values (54, 'Dakota', 'Dodge', 'Puce');
insert into model (id, model, brend, color) values (55, '240SX', 'Nissan', 'Orange');
insert into model (id, model, brend, color) values (56, 'Diamante', 'Mitsubishi', 'Purple');
insert into model (id, model, brend, color) values (57, 'Toronado', 'Oldsmobile', 'Aquamarine');
insert into model (id, model, brend, color) values (58, 'Explorer Sport Trac', 'Ford', 'Violet');
insert into model (id, model, brend, color) values (59, '600SL', 'Mercedes-Benz', 'Green');
insert into model (id, model, brend, color) values (60, 'DBS', 'Aston Martin', 'Khaki');
insert into model (id, model, brend, color) values (61, 'LR3', 'Land Rover', 'Violet');
insert into model (id, model, brend, color) values (62, 'Custom Cruiser', 'Oldsmobile', 'Goldenrod');
insert into model (id, model, brend, color) values (63, 'Topaz', 'Mercury', 'Teal');
insert into model (id, model, brend, color) values (64, '900', 'Saab', 'Red');
insert into model (id, model, brend, color) values (65, 'Town Car', 'Lincoln', 'Teal');
insert into model (id, model, brend, color) values (66, 'V50', 'Volvo', 'Purple');
insert into model (id, model, brend, color) values (67, 'XC70', 'Volvo', 'Mauv');
insert into model (id, model, brend, color) values (68, 'Maxima', 'Nissan', 'Teal');
insert into model (id, model, brend, color) values (69, 'Elise', 'Lotus', 'Pink');
insert into model (id, model, brend, color) values (70, 'Monterey', 'Mercury', 'Turquoise');
insert into model (id, model, brend, color) values (71, 'Allroad', 'Audi', 'Blue');
insert into model (id, model, brend, color) values (72, 'A4', 'Audi', 'Khaki');
insert into model (id, model, brend, color) values (73, 'GT', 'Ford', 'Pink');
insert into model (id, model, brend, color) values (74, 'Ranger', 'Ford', 'Crimson');
insert into model (id, model, brend, color) values (75, 'Z4', 'BMW', 'Orange');
insert into model (id, model, brend, color) values (76, 'C-Class', 'Mercedes-Benz', 'Maroon');
insert into model (id, model, brend, color) values (77, '7 Series', 'BMW', 'Violet');
insert into model (id, model, brend, color) values (78, 'Bronco', 'Ford', 'Mauv');
insert into model (id, model, brend, color) values (79, 'Express 1500', 'Chevrolet', 'Fuscia');
insert into model (id, model, brend, color) values (80, 'GS', 'Lexus', 'Yellow');
insert into model (id, model, brend, color) values (81, 'S-Type', 'Jaguar', 'Fuscia');
insert into model (id, model, brend, color) values (82, 'H1', 'Hummer', 'Teal');
insert into model (id, model, brend, color) values (83, 'Paseo', 'Toyota', 'Puce');
insert into model (id, model, brend, color) values (84, 'Echo', 'Toyota', 'Blue');
insert into model (id, model, brend, color) values (85, 'Charger', 'Dodge', 'Maroon');
insert into model (id, model, brend, color) values (86, 'CTS', 'Cadillac', 'Yellow');
insert into model (id, model, brend, color) values (87, 'Altima', 'Nissan', 'Indigo');
insert into model (id, model, brend, color) values (88, 'Murciélago', 'Lamborghini', 'Purple');
insert into model (id, model, brend, color) values (89, 'Cougar', 'Mercury', 'Purple');
insert into model (id, model, brend, color) values (90, '9-3', 'Saab', 'Purple');
insert into model (id, model, brend, color) values (91, 'Grand Am', 'Pontiac', 'Aquamarine');
insert into model (id, model, brend, color) values (92, 'Impala', 'Chevrolet', 'Green');
insert into model (id, model, brend, color) values (93, 'SX4', 'Suzuki', 'Fuscia');
insert into model (id, model, brend, color) values (94, '57', 'Maybach', 'Purple');
insert into model (id, model, brend, color) values (95, 'Cabriolet', 'Volkswagen', 'Maroon');
insert into model (id, model, brend, color) values (96, 'Accord', 'Honda', 'Crimson');
insert into model (id, model, brend, color) values (97, 'Town & Country', 'Chrysler', 'Blue');
insert into model (id, model, brend, color) values (98, 'Edge', 'Ford', 'Fuscia');
insert into model (id, model, brend, color) values (99, 'Allante', 'Cadillac', 'Purple');
insert into model (id, model, brend, color) values (100, 'M3', 'BMW', 'Teal');
insert into model (id, model, brend, color) values (101, 'Sentra', 'Nissan', 'Fuscia');
insert into model (id, model, brend, color) values (102, 'Aspen', 'Chrysler', 'Yellow');
insert into model (id, model, brend, color) values (103, 'Impala', 'Chevrolet', 'Green');
insert into model (id, model, brend, color) values (104, 'Grand Marquis', 'Mercury', 'Teal');
insert into model (id, model, brend, color) values (105, 'Safari', 'Pontiac', 'Maroon');
insert into model (id, model, brend, color) values (106, 'Silverado 2500', 'Chevrolet', 'Yellow');
insert into model (id, model, brend, color) values (107, 'Diamante', 'Mitsubishi', 'Green');
insert into model (id, model, brend, color) values (108, 'Yukon XL 2500', 'GMC', 'Indigo');
insert into model (id, model, brend, color) values (109, '370Z', 'Nissan', 'Indigo');
insert into model (id, model, brend, color) values (110, 'TSX', 'Acura', 'Teal');
insert into model (id, model, brend, color) values (111, 'IS', 'Lexus', 'Fuscia');
insert into model (id, model, brend, color) values (112, 'Vigor', 'Acura', 'Turquoise');
insert into model (id, model, brend, color) values (113, 'Corvette', 'Chevrolet', 'Pink');
insert into model (id, model, brend, color) values (114, '968', 'Porsche', 'Aquamarine');
insert into model (id, model, brend, color) values (115, 'Golf', 'Volkswagen', 'Orange');
insert into model (id, model, brend, color) values (116, 'Taurus', 'Ford', 'Yellow');
insert into model (id, model, brend, color) values (117, 'Tundra', 'Toyota', 'Red');
insert into model (id, model, brend, color) values (118, 'Taurus', 'Ford', 'Turquoise');
insert into model (id, model, brend, color) values (119, 'Grand Cherokee', 'Jeep', 'Mauv');
insert into model (id, model, brend, color) values (120, 'Intrepid', 'Dodge', 'Turquoise');
insert into model (id, model, brend, color) values (121, 'Silverado 2500', 'Chevrolet', 'Purple');
insert into model (id, model, brend, color) values (122, 'LX', 'Lexus', 'Aquamarine');
insert into model (id, model, brend, color) values (123, 'Grand Am', 'Pontiac', 'Aquamarine');
insert into model (id, model, brend, color) values (124, 'Savana 3500', 'GMC', 'Yellow');
insert into model (id, model, brend, color) values (125, 'Cayenne', 'Porsche', 'Fuscia');
insert into model (id, model, brend, color) values (126, '3500', 'Chevrolet', 'Purple');
insert into model (id, model, brend, color) values (127, 'Suburban 2500', 'Chevrolet', 'Crimson');
insert into model (id, model, brend, color) values (128, 'S60', 'Volvo', 'Goldenrod');
insert into model (id, model, brend, color) values (129, 'LX', 'Lexus', 'Mauv');
insert into model (id, model, brend, color) values (130, 'Carens', 'Kia', 'Indigo');
insert into model (id, model, brend, color) values (131, 'Cayenne', 'Porsche', 'Mauv');
insert into model (id, model, brend, color) values (132, 'Aspire', 'Ford', 'Aquamarine');
insert into model (id, model, brend, color) values (133, 'Galant', 'Mitsubishi', 'Green');
insert into model (id, model, brend, color) values (134, 'Expedition EL', 'Ford', 'Blue');
insert into model (id, model, brend, color) values (135, 'Avalon', 'Toyota', 'Orange');
insert into model (id, model, brend, color) values (136, 'RL', 'Acura', 'Aquamarine');
insert into model (id, model, brend, color) values (137, 'Achieva', 'Oldsmobile', 'Red');
insert into model (id, model, brend, color) values (138, 'Ram Van B150', 'Dodge', 'Fuscia');
insert into model (id, model, brend, color) values (139, 'Cherokee', 'Jeep', 'Crimson');
insert into model (id, model, brend, color) values (140, 'Crown Victoria', 'Ford', 'Turquoise');
insert into model (id, model, brend, color) values (141, 'Cabriolet', 'Volkswagen', 'Khaki');
insert into model (id, model, brend, color) values (142, '2500 Club Coupe', 'GMC', 'Red');
insert into model (id, model, brend, color) values (143, 'MPV', 'Mazda', 'Green');
insert into model (id, model, brend, color) values (144, 'Sportage', 'Kia', 'Green');
insert into model (id, model, brend, color) values (145, 'Golf', 'Volkswagen', 'Yellow');
insert into model (id, model, brend, color) values (146, '8 Series', 'BMW', 'Indigo');
insert into model (id, model, brend, color) values (147, 'Vandura 2500', 'GMC', 'Aquamarine');
insert into model (id, model, brend, color) values (148, 'Aspen', 'Dodge', 'Khaki');
insert into model (id, model, brend, color) values (149, 'Odyssey', 'Honda', 'Red');
insert into model (id, model, brend, color) values (150, 'SL-Class', 'Mercedes-Benz', 'Turquoise');
insert into model (id, model, brend, color) values (151, 'Lancer Evolution', 'Mitsubishi', 'Red');
insert into model (id, model, brend, color) values (152, 'Blazer', 'Chevrolet', 'Mauv');
insert into model (id, model, brend, color) values (153, 'Camry', 'Toyota', 'Mauv');
insert into model (id, model, brend, color) values (154, 'Type 2', 'Volkswagen', 'Crimson');
insert into model (id, model, brend, color) values (155, 'Leaf', 'Nissan', 'Teal');
insert into model (id, model, brend, color) values (156, 'QX56', 'Infiniti', 'Maroon');
insert into model (id, model, brend, color) values (157, '1500', 'Chevrolet', 'Khaki');
insert into model (id, model, brend, color) values (158, '240SX', 'Nissan', 'Fuscia');
insert into model (id, model, brend, color) values (159, 'Phantom', 'Rolls-Royce', 'Red');
insert into model (id, model, brend, color) values (160, 'Landaulet', 'Maybach', 'Goldenrod');
insert into model (id, model, brend, color) values (161, 'Ridgeline', 'Honda', 'Puce');
insert into model (id, model, brend, color) values (162, '57S', 'Maybach', 'Fuscia');
insert into model (id, model, brend, color) values (163, 'Elise', 'Lotus', 'Orange');
insert into model (id, model, brend, color) values (164, 'Spectra', 'Kia', 'Khaki');
insert into model (id, model, brend, color) values (165, 'Dakota', 'Dodge', 'Blue');
insert into model (id, model, brend, color) values (166, 'Mark VIII', 'Lincoln', 'Turquoise');
insert into model (id, model, brend, color) values (167, 'Grand Prix', 'Pontiac', 'Orange');
insert into model (id, model, brend, color) values (168, 'CR-V', 'Honda', 'Fuscia');
insert into model (id, model, brend, color) values (169, 'Corsica', 'Chevrolet', 'Blue');
insert into model (id, model, brend, color) values (170, '9-5', 'Saab', 'Mauv');
insert into model (id, model, brend, color) values (171, 'Blazer', 'Chevrolet', 'Violet');
insert into model (id, model, brend, color) values (172, '4Runner', 'Toyota', 'Puce');
insert into model (id, model, brend, color) values (173, 'Civic', 'Honda', 'Green');
insert into model (id, model, brend, color) values (174, 'Escape', 'Ford', 'Blue');
insert into model (id, model, brend, color) values (175, 'Montego', 'Mercury', 'Crimson');
insert into model (id, model, brend, color) values (176, 'Monza', 'Chevrolet', 'Teal');
insert into model (id, model, brend, color) values (177, 'Xterra', 'Nissan', 'Violet');
insert into model (id, model, brend, color) values (178, 'Rendezvous', 'Buick', 'Indigo');
insert into model (id, model, brend, color) values (179, '745', 'BMW', 'Goldenrod');
insert into model (id, model, brend, color) values (180, 'Murano', 'Nissan', 'Maroon');
insert into model (id, model, brend, color) values (181, 'Rogue', 'Nissan', 'Turquoise');
insert into model (id, model, brend, color) values (182, 'Cayenne', 'Porsche', 'Blue');
insert into model (id, model, brend, color) values (183, 'V70', 'Volvo', 'Mauv');
insert into model (id, model, brend, color) values (184, 'ES', 'Lexus', 'Crimson');
insert into model (id, model, brend, color) values (185, 'Fiero', 'Pontiac', 'Red');
insert into model (id, model, brend, color) values (186, 'DB9', 'Aston Martin', 'Indigo');
insert into model (id, model, brend, color) values (187, 'DeVille', 'Cadillac', 'Green');
insert into model (id, model, brend, color) values (188, 'Diamante', 'Mitsubishi', 'Turquoise');
insert into model (id, model, brend, color) values (189, 'LX', 'Lexus', 'Yellow');
insert into model (id, model, brend, color) values (190, 'LX', 'Lexus', 'Khaki');
insert into model (id, model, brend, color) values (191, 'Grand Voyager', 'Plymouth', 'Goldenrod');
insert into model (id, model, brend, color) values (192, 'Yukon XL 2500', 'GMC', 'Green');
insert into model (id, model, brend, color) values (193, 'Rio', 'Kia', 'Purple');
insert into model (id, model, brend, color) values (194, 'SX4', 'Suzuki', 'Fuscia');
insert into model (id, model, brend, color) values (195, 'F150', 'Ford', 'Turquoise');
insert into model (id, model, brend, color) values (196, 'TundraMax', 'Toyota', 'Fuscia');
insert into model (id, model, brend, color) values (197, 'Savana', 'GMC', 'Mauv');
insert into model (id, model, brend, color) values (198, 'Swift', 'Suzuki', 'Green');
insert into model (id, model, brend, color) values (199, 'CX-9', 'Mazda', 'Mauv');
insert into model (id, model, brend, color) values (200, 'Z4', 'BMW', 'Teal');
insert into model (id, model, brend, color) values (201, 'Regency', 'Oldsmobile', 'Teal');
insert into model (id, model, brend, color) values (202, 'E350', 'Ford', 'Orange');
insert into model (id, model, brend, color) values (203, '9000', 'Saab', 'Fuscia');
insert into model (id, model, brend, color) values (204, '626', 'Mazda', 'Orange');
insert into model (id, model, brend, color) values (205, 'Echo', 'Toyota', 'Yellow');
insert into model (id, model, brend, color) values (206, 'Fairlane', 'Ford', 'Violet');
insert into model (id, model, brend, color) values (207, 'Rocky', 'Daihatsu', 'Indigo');
insert into model (id, model, brend, color) values (208, 'RAV4', 'Toyota', 'Purple');
insert into model (id, model, brend, color) values (209, 'Torrent', 'Pontiac', 'Pink');
insert into model (id, model, brend, color) values (210, 'Express 2500', 'Chevrolet', 'Maroon');
insert into model (id, model, brend, color) values (211, 'Metro', 'Chevrolet', 'Green');
insert into model (id, model, brend, color) values (212, '3500', 'GMC', 'Violet');
insert into model (id, model, brend, color) values (213, 'Savana 1500', 'GMC', 'Orange');
insert into model (id, model, brend, color) values (214, 'CTS-V', 'Cadillac', 'Goldenrod');
insert into model (id, model, brend, color) values (215, 'XJ Series', 'Jaguar', 'Puce');
insert into model (id, model, brend, color) values (216, 'Yukon', 'GMC', 'Turquoise');
insert into model (id, model, brend, color) values (217, 'Eclipse', 'Mitsubishi', 'Fuscia');
insert into model (id, model, brend, color) values (218, 'Avalanche 2500', 'Chevrolet', 'Mauv');
insert into model (id, model, brend, color) values (219, 'Challenger', 'Mitsubishi', 'Yellow');
insert into model (id, model, brend, color) values (220, 'Breeze', 'Plymouth', 'Blue');
insert into model (id, model, brend, color) values (221, 'Probe', 'Ford', 'Yellow');
insert into model (id, model, brend, color) values (222, 'E150', 'Ford', 'Orange');
insert into model (id, model, brend, color) values (223, 'Freelander', 'Land Rover', 'Mauv');
insert into model (id, model, brend, color) values (224, 'Wrangler', 'Jeep', 'Teal');
insert into model (id, model, brend, color) values (225, 'Focus', 'Ford', 'Purple');
insert into model (id, model, brend, color) values (226, 'Diablo', 'Lamborghini', 'Aquamarine');
insert into model (id, model, brend, color) values (227, 'Maxima', 'Nissan', 'Pink');
insert into model (id, model, brend, color) values (228, 'GTI', 'Volkswagen', 'Mauv');
insert into model (id, model, brend, color) values (229, 'Corrado', 'Volkswagen', 'Indigo');
insert into model (id, model, brend, color) values (230, 'Yukon XL 1500', 'GMC', 'Puce');
insert into model (id, model, brend, color) values (231, 'Tacoma Xtra', 'Toyota', 'Pink');
insert into model (id, model, brend, color) values (232, 'E-Class', 'Mercedes-Benz', 'Violet');
insert into model (id, model, brend, color) values (233, 'E-Class', 'Mercedes-Benz', 'Maroon');
insert into model (id, model, brend, color) values (234, 'FX', 'Infiniti', 'Violet');
insert into model (id, model, brend, color) values (235, 'F250', 'Ford', 'Purple');
insert into model (id, model, brend, color) values (236, 'G37', 'Infiniti', 'Khaki');
insert into model (id, model, brend, color) values (237, 'Grand Prix', 'Pontiac', 'Crimson');
insert into model (id, model, brend, color) values (238, 'LS', 'Lexus', 'Crimson');
insert into model (id, model, brend, color) values (239, '3500 Club Coupe', 'GMC', 'Indigo');
insert into model (id, model, brend, color) values (240, '7 Series', 'BMW', 'Red');
insert into model (id, model, brend, color) values (241, 'Silverado 2500', 'Chevrolet', 'Orange');
insert into model (id, model, brend, color) values (242, 'XC90', 'Volvo', 'Red');
insert into model (id, model, brend, color) values (243, 'Navigator', 'Lincoln', 'Red');
insert into model (id, model, brend, color) values (244, 'Regal', 'Buick', 'Yellow');
insert into model (id, model, brend, color) values (245, 'RL', 'Acura', 'Red');
insert into model (id, model, brend, color) values (246, 'FX', 'Infiniti', 'Pink');
insert into model (id, model, brend, color) values (247, 'C-Class', 'Mercedes-Benz', 'Crimson');
insert into model (id, model, brend, color) values (248, 'Ridgeline', 'Honda', 'Red');
insert into model (id, model, brend, color) values (249, 'RX-7', 'Mazda', 'Red');
insert into model (id, model, brend, color) values (250, 'ES', 'Lexus', 'Indigo');
insert into model (id, model, brend, color) values (251, 'Ascender', 'Isuzu', 'Mauv');
insert into model (id, model, brend, color) values (252, 'Ranger', 'Ford', 'Fuscia');
insert into model (id, model, brend, color) values (253, 'Grand Voyager', 'Plymouth', 'Green');
insert into model (id, model, brend, color) values (254, 'PT Cruiser', 'Chrysler', 'Maroon');
insert into model (id, model, brend, color) values (255, 'Caravan', 'Dodge', 'Goldenrod');
insert into model (id, model, brend, color) values (256, 'Terrain', 'GMC', 'Yellow');
insert into model (id, model, brend, color) values (257, 'PT Cruiser', 'Chrysler', 'Pink');
insert into model (id, model, brend, color) values (258, 'E350', 'Ford', 'Purple');
insert into model (id, model, brend, color) values (259, 'Mustang', 'Ford', 'Maroon');
insert into model (id, model, brend, color) values (260, 'Vandura 1500', 'GMC', 'Turquoise');
insert into model (id, model, brend, color) values (261, 'Aveo', 'Chevrolet', 'Purple');
insert into model (id, model, brend, color) values (262, 'Jetta', 'Volkswagen', 'Indigo');
insert into model (id, model, brend, color) values (263, 'E-Class', 'Mercedes-Benz', 'Pink');
insert into model (id, model, brend, color) values (264, '960', 'Volvo', 'Green');
insert into model (id, model, brend, color) values (265, 'Tempo', 'Ford', 'Red');
insert into model (id, model, brend, color) values (266, 'S4', 'Audi', 'Purple');
insert into model (id, model, brend, color) values (267, 'Lumina APV', 'Chevrolet', 'Purple');
insert into model (id, model, brend, color) values (268, '400SE', 'Mercedes-Benz', 'Goldenrod');
insert into model (id, model, brend, color) values (269, 'Patriot', 'Jeep', 'Blue');
insert into model (id, model, brend, color) values (270, 'Grand Caravan', 'Dodge', 'Pink');
insert into model (id, model, brend, color) values (271, 'S60', 'Volvo', 'Goldenrod');
insert into model (id, model, brend, color) values (272, 'S-Class', 'Mercedes-Benz', 'Khaki');
insert into model (id, model, brend, color) values (273, 'Tiburon', 'Hyundai', 'Fuscia');
insert into model (id, model, brend, color) values (274, '9-3', 'Saab', 'Khaki');
insert into model (id, model, brend, color) values (275, 'SL65 AMG', 'Mercedes-Benz', 'Crimson');
insert into model (id, model, brend, color) values (276, 'Camry', 'Toyota', 'Khaki');
insert into model (id, model, brend, color) values (277, 'Frontier', 'Nissan', 'Yellow');
insert into model (id, model, brend, color) values (278, 'Suburban 1500', 'Chevrolet', 'Yellow');
insert into model (id, model, brend, color) values (279, 'Montana', 'Pontiac', 'Turquoise');
insert into model (id, model, brend, color) values (280, 'Panamera', 'Porsche', 'Maroon');
insert into model (id, model, brend, color) values (281, 'Swift', 'Suzuki', 'Aquamarine');
insert into model (id, model, brend, color) values (282, 'J', 'Infiniti', 'Indigo');
insert into model (id, model, brend, color) values (283, 'Thunderbird', 'Ford', 'Pink');
insert into model (id, model, brend, color) values (284, 'XL-7', 'Suzuki', 'Mauv');
insert into model (id, model, brend, color) values (285, 'Grand Caravan', 'Dodge', 'Indigo');
insert into model (id, model, brend, color) values (286, 'Silverado 2500', 'Chevrolet', 'Orange');
insert into model (id, model, brend, color) values (287, 'X-Type', 'Jaguar', 'Blue');
insert into model (id, model, brend, color) values (288, 'Express 1500', 'Chevrolet', 'Purple');
insert into model (id, model, brend, color) values (289, 'E350', 'Ford', 'Maroon');
insert into model (id, model, brend, color) values (290, '4000', 'Audi', 'Goldenrod');
insert into model (id, model, brend, color) values (291, 'Ranger', 'Ford', 'Aquamarine');
insert into model (id, model, brend, color) values (292, 'Caliber', 'Dodge', 'Yellow');
insert into model (id, model, brend, color) values (293, 'C70', 'Volvo', 'Crimson');
insert into model (id, model, brend, color) values (294, 'Suburban 1500', 'GMC', 'Pink');
insert into model (id, model, brend, color) values (295, 'FX', 'Infiniti', 'Purple');
insert into model (id, model, brend, color) values (296, 'GS', 'Lexus', 'Maroon');
insert into model (id, model, brend, color) values (297, 'Venture', 'Chevrolet', 'Yellow');
insert into model (id, model, brend, color) values (298, 'GTI', 'Volkswagen', 'Orange');
insert into model (id, model, brend, color) values (299, 'Daewoo Magnus', 'Suzuki', 'Turquoise');
insert into model (id, model, brend, color) values (300, 'E-Class', 'Mercedes-Benz', 'Red');
